/**
 * Fallback for the Top 100 until the ranking job has written a snapshot
 * (fresh database, or the job disabled in dev/CI). Generated from a real run
 * of the job (SEC EDGAR shares × IEX last) — not hand-ranked. Regenerate by
 * running the job and copying its newest snapshot; never presented as live.
 */
export const TOP100_SEED_AS_OF = "2026-09-30";

export const TOP100_SEED_ENTRIES: ReadonlyArray<{ rank: number; symbol: string; name: string }> = [
  { rank: 1, symbol: "NVDA", name: "NVIDIA" },
  { rank: 2, symbol: "AAPL", name: "Apple" },
  { rank: 3, symbol: "GOOGL", name: "Alphabet" },
  { rank: 4, symbol: "MSFT", name: "Microsoft" },
  { rank: 5, symbol: "AMZN", name: "Amazon" },
  { rank: 6, symbol: "META", name: "Meta Platforms" },
  { rank: 7, symbol: "AVGO", name: "Broadcom" },
  { rank: 8, symbol: "TSLA", name: "Tesla" },
  { rank: 9, symbol: "MU", name: "Micron Technology Inc." },
  { rank: 10, symbol: "LLY", name: "Eli Lilly" },
  { rank: 11, symbol: "BRK.B", name: "Berkshire Hathaway" },
  { rank: 12, symbol: "AMD", name: "Advanced Micro Devices" },
  { rank: 13, symbol: "JPM", name: "JPMorgan Chase" },
  { rank: 14, symbol: "SPCX", name: "Space Exploration Technologies Corp." },
  { rank: 15, symbol: "WMT", name: "Walmart" },
  { rank: 16, symbol: "V", name: "Visa" },
  { rank: 17, symbol: "XOM", name: "Exxon Mobil" },
  { rank: 18, symbol: "JNJ", name: "Johnson & Johnson" },
  { rank: 19, symbol: "INTC", name: "Intel" },
  { rank: 20, symbol: "MA", name: "Mastercard" },
  { rank: 21, symbol: "ABBV", name: "AbbVie" },
  { rank: 22, symbol: "PLTR", name: "Palantir Technologies Inc." },
  { rank: 23, symbol: "CSCO", name: "Cisco Systems" },
  { rank: 24, symbol: "ORCL", name: "Oracle" },
  { rank: 25, symbol: "LRCX", name: "Lam Research Corp." },
  { rank: 26, symbol: "AMAT", name: "Applied Materials Inc." },
  { rank: 27, symbol: "COST", name: "Costco" },
  { rank: 28, symbol: "CVX", name: "Chevron" },
  { rank: 29, symbol: "BAC", name: "Bank of America" },
  { rank: 30, symbol: "CAT", name: "Caterpillar" },
  { rank: 31, symbol: "KO", name: "Coca-Cola" },
  { rank: 32, symbol: "MRK", name: "Merck" },
  { rank: 33, symbol: "DELL", name: "Dell Technologies Inc." },
  { rank: 34, symbol: "PG", name: "Procter & Gamble" },
  { rank: 35, symbol: "UNH", name: "UnitedHealth Group" },
  { rank: 36, symbol: "PANW", name: "Palo Alto Networks Inc." },
  { rank: 37, symbol: "GE", name: "GE Aerospace" },
  { rank: 38, symbol: "PM", name: "Philip Morris International" },
  { rank: 39, symbol: "MS", name: "Morgan Stanley" },
  { rank: 40, symbol: "NFLX", name: "Netflix" },
  { rank: 41, symbol: "HD", name: "Home Depot" },
  { rank: 42, symbol: "CRWD", name: "CrowdStrike Holdings, Inc." },
  { rank: 43, symbol: "GS", name: "Goldman Sachs" },
  { rank: 44, symbol: "ANET", name: "Arista Networks, Inc." },
  { rank: 45, symbol: "SNDK", name: "Sandisk Corp." },
  { rank: 46, symbol: "TXN", name: "Texas Instruments Inc." },
  { rank: 47, symbol: "KLAC", name: "KLA Corp." },
  { rank: 48, symbol: "GEV", name: "GE Vernova Inc." },
  { rank: 49, symbol: "RTX", name: "RTX" },
  { rank: 50, symbol: "TMO", name: "Thermo Fisher Scientific" },
  { rank: 51, symbol: "WFC", name: "Wells Fargo" },
  { rank: 52, symbol: "MRVL", name: "Marvell Technology, Inc." },
  { rank: 53, symbol: "AMGN", name: "Amgen Inc." },
  { rank: 54, symbol: "LIN", name: "Linde" },
  { rank: 55, symbol: "C", name: "Citigroup Inc." },
  { rank: 56, symbol: "STX", name: "Seagate Technology Holdings plc" },
  { rank: 57, symbol: "IBM", name: "International Business Machines Corp." },
  { rank: 58, symbol: "AXP", name: "American Express" },
  { rank: 59, symbol: "QCOM", name: "Qualcomm Inc." },
  { rank: 60, symbol: "SHOP", name: "Shopify Inc." },
  { rank: 61, symbol: "ADI", name: "Analog Devices Inc." },
  { rank: 62, symbol: "VZ", name: "Verizon" },
  { rank: 63, symbol: "CRM", name: "Salesforce" },
  { rank: 64, symbol: "GILD", name: "Gilead Sciences, Inc." },
  { rank: 65, symbol: "DIS", name: "Walt Disney" },
  { rank: 66, symbol: "DE", name: "Deere & Company" },
  { rank: 67, symbol: "TMUS", name: "T-Mobile US" },
  { rank: 68, symbol: "PEP", name: "PepsiCo" },
  { rank: 69, symbol: "ABT", name: "Abbott Laboratories" },
  { rank: 70, symbol: "T", name: "AT&T" },
  { rank: 71, symbol: "SCCO", name: "Southern Copper Corp./" },
  { rank: 72, symbol: "SCHW", name: "Schwab Charles Corp." },
  { rank: 73, symbol: "ETN", name: "Eaton Corp. plc" },
  { rank: 74, symbol: "WELL", name: "Welltower" },
  { rank: 75, symbol: "BLK", name: "BlackRock, Inc." },
  { rank: 76, symbol: "MCD", name: "McDonald's" },
  { rank: 77, symbol: "WDC", name: "Western Digital Corp." },
  { rank: 78, symbol: "PFE", name: "Pfizer" },
  { rank: 79, symbol: "UNP", name: "Union Pacific" },
  { rank: 80, symbol: "NEE", name: "NextEra Energy" },
  { rank: 81, symbol: "DHR", name: "Danaher Corp." },
  { rank: 82, symbol: "COP", name: "ConocoPhillips" },
  { rank: 83, symbol: "BA", name: "Boeing" },
  { rank: 84, symbol: "TJX", name: "TJX Companies Inc." },
  { rank: 85, symbol: "ISRG", name: "Intuitive Surgical Inc." },
  { rank: 86, symbol: "UBER", name: "Uber Technologies, Inc." },
  { rank: 87, symbol: "NOW", name: "ServiceNow, Inc." },
  { rank: 88, symbol: "VRTX", name: "Vertex Pharmaceuticals Inc. / MA" },
  { rank: 89, symbol: "GLW", name: "Corning Inc." },
  { rank: 90, symbol: "FTNT", name: "Fortinet, Inc." },
  { rank: 91, symbol: "BMY", name: "Bristol Myers Squibb Co." },
  { rank: 92, symbol: "CB", name: "Chubb Ltd." },
  { rank: 93, symbol: "NET", name: "Cloudflare, Inc." },
  { rank: 94, symbol: "NEM", name: "Newmont" },
  { rank: 95, symbol: "BKNG", name: "Booking Holdings" },
  { rank: 96, symbol: "PLD", name: "Prologis" },
  { rank: 97, symbol: "PGR", name: "Progressive Corp." },
  { rank: 98, symbol: "PH", name: "Parker-Hannifin Corp." },
  { rank: 99, symbol: "SNOW", name: "Snowflake Inc." },
  { rank: 100, symbol: "COF", name: "Capital One Financial Corp." },
];
